#!/usr/bin/env ruby

require "thor"
require "bundler/setup"
require "todo"

class TodoCLI < Thor
  desc("add ITEM", "adds item to list")
  option :database, default: "~/.todo"

  def add(item)
    config = {
      database: File.open(File.expand_path(options[:database]), "a+")
    }
    Todo::Manager.new(config).add(item)
  end #add

  def remove(item)
    config = {
      database: File.open(File.expand_path(options[:database]), "a+")
    }
    Todo::Manager.new(config).add(item)
  end #remove
end #TodoCLI

TodoCLI.start(ARGV)